### ISSUE TITLE
Improve test output handling

### ISSUE THREAD

**Issue by hbenl** [microsoft/vscode-test-adapter-converter#17] opened 2021-08-08 14:30 UTC
Test adapters can send output from tests to Test Explorer and this converter will pass those messages to the native testing API using `vscode.TestRun.appendOutput()`. But I can't find these messages anywhere in the UI, only the messages sent to `vscode.TestRun.failed()` or `vscode.TestRun.errored()`.
Furthermore, output sent to Test Explorer can be associated with a running test, but the native testing API doesn't seem to support that (except for error messages). This can be very useful because you don't have to wade through all messages from a test run to find the messages from a particular test.

**Comment by connor4312** [comment] 2021-08-11 13:14
`appendOutput` strings are shown in the Test Output, which can be seen using the `Test: Show Output` command, also accessible via the `ctrl+; ctrl+o` chord or via the "terminal" icon in the test explorer view.

> output sent to Test Explorer can be associated with a running test, but the native testing API doesn't seem to support that (except for error messages

That's requested in https://github.com/microsoft/vscode/issues/129201 and should come this month. Closing this as a dupe of that one 🙂

**Closed by connor4312** 2021-08-11 13:14 UTC
